global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'observability-backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['monitoring-service:8081', 'incident-service:8082', 'chatops-service:8083']
