spring:
  application:
    name: monitoring-service
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: monitoring-service

incident:
  service:
    url: ${INCIDENT_SERVICE_URL:http://localhost:8082}
